"""add_dealers_json_to_competitors

Revision ID: ae0c17cdd7e6
Revises: c8d5e2f3a4b7
Create Date: 2026-06-08 12:49:27.130560+03:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0c17cdd7e6'
down_revision = 'c8d5e2f3a4b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_analyses_article_id_key', 'article_analyses', type_='unique')
    op.drop_index('ix_article_analyses_article_id', table_name='article_analyses')
    op.create_index(op.f('ix_article_analyses_article_id'), 'article_analyses', ['article_id'], unique=True)
    op.add_column('competitors', sa.Column('dealers', sa.JSON(), nullable=True))
    op.drop_index('idx_knowledge_fts', table_name='knowledge_articles', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_knowledge_fts', 'knowledge_articles', [sa.text("to_tsvector('russian'::regconfig, (body_md || ' '::text) || title::text)")], unique=False, postgresql_using='gin')
    op.drop_column('competitors', 'dealers')
    op.drop_index(op.f('ix_article_analyses_article_id'), table_name='article_analyses')
    op.create_index('ix_article_analyses_article_id', 'article_analyses', ['article_id'], unique=False)
    op.create_unique_constraint('article_analyses_article_id_key', 'article_analyses', ['article_id'])
    # ### end Alembic commands ###
