"""add_knowledge_facts_chunks_product_hierarchy

Revision ID: 36366251cf5d
Revises: c3d4e5f6a7b8
Create Date: 2026-06-14 21:18:19.506522+03:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36366251cf5d'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('char_offset_start', sa.Integer(), nullable=True),
    sa.Column('char_offset_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_article_id'), 'knowledge_chunks', ['article_id'], unique=False)
    op.create_table('knowledge_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.Enum('PRODUCT', 'BRINE', 'CHAMBER', 'TECHNOLOGY', 'INGREDIENT', 'REGULATION', 'ARTICLE', name='fact_subject_type'), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('predicate', sa.Enum('USES_BRINE', 'USES_EQUIPMENT', 'USES_TECHNOLOGY', 'HAS_PARAMETER', 'REGULATED_BY', 'HAS_CATEGORY', 'CONTAINS', 'DERIVED_FROM', 'SHELF_LIFE', 'STORAGE_CONDITION', 'PROCESS_STEP', 'MENTIONS', name='fact_predicate'), nullable=False),
    sa.Column('object_type', sa.Enum('PRODUCT', 'BRINE', 'CHAMBER', 'TECHNOLOGY', 'REGULATION', 'INGREDIENT', 'LITERAL', name='fact_object_type'), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('object_name', sa.String(length=500), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('CANDIDATE', 'CONFIRMED', 'CONTRADICTED', 'DEPRECATED', name='fact_status'), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_facts_article_id'), 'knowledge_facts', ['article_id'], unique=False)
    op.create_index(op.f('ix_knowledge_facts_chunk_id'), 'knowledge_facts', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_knowledge_facts_predicate'), 'knowledge_facts', ['predicate'], unique=False)
    op.create_index(op.f('ix_knowledge_facts_source_hash'), 'knowledge_facts', ['source_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_facts_subject_type'), 'knowledge_facts', ['subject_type'], unique=False)
    op.add_column('products', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_parent_id'), 'products', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'products', 'products', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_parent_id'), table_name='products')
    op.drop_column('products', 'parent_id')
    op.drop_index(op.f('ix_knowledge_facts_subject_type'), table_name='knowledge_facts')
    op.drop_index(op.f('ix_knowledge_facts_source_hash'), table_name='knowledge_facts')
    op.drop_index(op.f('ix_knowledge_facts_predicate'), table_name='knowledge_facts')
    op.drop_index(op.f('ix_knowledge_facts_chunk_id'), table_name='knowledge_facts')
    op.drop_index(op.f('ix_knowledge_facts_article_id'), table_name='knowledge_facts')
    op.drop_table('knowledge_facts')
    op.drop_index(op.f('ix_knowledge_chunks_article_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
