"""add_competitor_model_fields

Revision ID: 6cdd62d07710
Revises: d87feba3f3c5
Create Date: 2026-06-03 14:43:42.046458+03:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdd62d07710'
down_revision = 'd87feba3f3c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_models', sa.Column('weight_kg', sa.Integer(), nullable=True))
    op.add_column('competitor_models', sa.Column('dimensions', sa.String(length=100), nullable=True))
    op.add_column('competitor_models', sa.Column('modes', sa.JSON(), nullable=True))
    op.add_column('competitor_models', sa.Column('automation_level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor_models', 'automation_level')
    op.drop_column('competitor_models', 'modes')
    op.drop_column('competitor_models', 'dimensions')
    op.drop_column('competitor_models', 'weight_kg')
    # ### end Alembic commands ###
