"""initial models

Revision ID: 529ad78b1f74
Revises: 
Create Date: 2026-06-03 10:47:14.299804+03:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529ad78b1f74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('method', sa.Enum('DRY', 'WET', 'INJECTION', 'COMBO', 'MIXED', name='brine_method'), nullable=False),
    sa.Column('salt_percent', sa.Float(), nullable=False),
    sa.Column('sugar_percent', sa.Float(), nullable=False),
    sa.Column('nitrite_ppm', sa.Float(), nullable=False),
    sa.Column('nitrate_ppm', sa.Float(), nullable=False),
    sa.Column('spices', sa.JSON(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('water_percent', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brines_slug'), 'brines', ['slug'], unique=True)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('MEAT', 'FAT', 'SPICE', 'SALT', 'WOOD', 'LIQUID_SMOKE', 'ADDITIVE', 'OTHER', name='ingredient_type'), nullable=False),
    sa.Column('protein_per_100g', sa.Float(), nullable=False),
    sa.Column('fat_per_100g', sa.Float(), nullable=False),
    sa.Column('carbs_per_100g', sa.Float(), nullable=False),
    sa.Column('kcal_per_100g', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_allergen', sa.Boolean(), nullable=False),
    sa.Column('allergens', sa.JSON(), nullable=False),
    sa.Column('gmo_flag', sa.Boolean(), nullable=False),
    sa.Column('wood_species', sa.String(length=50), nullable=True),
    sa.Column('wood_form', sa.String(length=50), nullable=True),
    sa.Column('fraction_mm', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_slug'), 'ingredients', ['slug'], unique=True)
    op.create_index(op.f('ix_ingredients_type'), 'ingredients', ['type'], unique=False)
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_our_brand', sa.Boolean(), nullable=False),
    sa.Column('is_competitor', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_is_competitor'), 'manufacturers', ['is_competitor'], unique=False)
    op.create_index(op.f('ix_manufacturers_is_our_brand'), 'manufacturers', ['is_our_brand'], unique=False)
    op.create_index(op.f('ix_manufacturers_slug'), 'manufacturers', ['slug'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('SAUSAGE_BOILD', 'SAUSAGE_SEMI_SMOKED', 'SAUSAGE_RAW_SMOKED', 'MEAT', 'POULTRY', 'FISH_HOT', 'FISH_COLD', 'FISH_ELECTRO', 'CHEESE', 'SAUSAGE_SALAMI', 'BACON', 'BUTTER', 'SNACKS', 'OTHER', name='product_category'), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('base_recipe_id', sa.Integer(), nullable=True),
    sa.Column('gost', sa.String(length=100), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('storage_temp_min', sa.Float(), nullable=True),
    sa.Column('storage_temp_max', sa.Float(), nullable=True),
    sa.Column('storage_humidity_min', sa.Float(), nullable=True),
    sa.Column('storage_humidity_max', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_recipe_id'], ['recipes.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TECHNOLOGIST', 'OPERATOR', 'MANAGER', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'REJECT', 'LOGIN', 'LOGOUT', 'START', 'PAUSE', 'RESUME', 'STOP', 'CANCEL', 'COMPLETE', 'EXPORT', 'IMPORT', 'OTHER', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_ts'), 'audit_logs', ['ts'], unique=False)
    op.create_table('chambers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('HOT', 'COLD', 'ELECTRO', 'UNIVERSAL', 'SEMI_HOT', 'SMOKE', 'UNKNOWN', name='chamber_type'), nullable=False),
    sa.Column('max_load_kg', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('power_kw', sa.Float(), nullable=True),
    sa.Column('voltage_v', sa.Integer(), nullable=True),
    sa.Column('supports_static_smoke', sa.Boolean(), nullable=False),
    sa.Column('supports_electro', sa.Boolean(), nullable=False),
    sa.Column('supports_cold_smoke', sa.Boolean(), nullable=False),
    sa.Column('supports_cooling', sa.Boolean(), nullable=False),
    sa.Column('supports_freezing', sa.Boolean(), nullable=False),
    sa.Column('supports_joint', sa.Boolean(), nullable=False),
    sa.Column('supported_protocols', sa.JSON(), nullable=False),
    sa.Column('driver_class', sa.String(length=100), nullable=False),
    sa.Column('default_driver_config', sa.JSON(), nullable=False),
    sa.Column('num_chambers', sa.Integer(), nullable=False),
    sa.Column('num_carts', sa.Integer(), nullable=False),
    sa.Column('num_probes', sa.Integer(), nullable=False),
    sa.Column('max_program_phases', sa.Integer(), nullable=False),
    sa.Column('price_rrp_rub', sa.Float(), nullable=True),
    sa.Column('price_dealer_rub', sa.Float(), nullable=True),
    sa.Column('price_rrp_eur', sa.Float(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chambers_manufacturer_id'), 'chambers', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_chambers_slug'), 'chambers', ['slug'], unique=True)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.Enum('THEORY', 'RECIPE', 'TROUBLESHOOTING', 'REGULATION', 'COMPARISON', 'REVIEW', 'NEWS', 'GUIDE', name='article_category'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('chamber_model', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_category'), 'knowledge_articles', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_slug'), 'knowledge_articles', ['slug'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'ARCHIVED', name='recipe_status'), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_version_id'], ['recipe_versions.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_product_id'), 'recipes', ['product_id'], unique=False)
    op.create_index(op.f('ix_recipes_slug'), 'recipes', ['slug'], unique=True)
    op.create_index(op.f('ix_recipes_status'), 'recipes', ['status'], unique=False)
    op.create_table('knowledge_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('PDF', 'VIDEO', 'IMAGE', 'DOC', 'LINK', name='attachment_kind'), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_attachments_article_id'), 'knowledge_attachments', ['article_id'], unique=False)
    op.create_table('recipe_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('program', sa.JSON(), nullable=False),
    sa.Column('brine', sa.JSON(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('yield_percent', sa.Float(), nullable=True),
    sa.Column('losses_percent', sa.Float(), nullable=True),
    sa.Column('bju_per_100g', sa.JSON(), nullable=True),
    sa.Column('cost_per_kg', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gost', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'ARCHIVED', name='recipe_version_status'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['recipe_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'version_number', name='uq_recipe_version_number')
    )
    op.create_index(op.f('ix_recipe_versions_recipe_id'), 'recipe_versions', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_versions_status'), 'recipe_versions', ['status'], unique=False)
    op.create_table('telemetry_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chamber_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('t_chamber', sa.Float(), nullable=True),
    sa.Column('t_product', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('smoke_density', sa.Float(), nullable=True),
    sa.Column('electro_voltage', sa.Float(), nullable=True),
    sa.Column('electro_current', sa.Float(), nullable=True),
    sa.Column('fan_rpm', sa.Float(), nullable=True),
    sa.Column('door_open', sa.Boolean(), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=True),
    sa.Column('phase_progress', sa.Float(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telemetry_chamber_ts', 'telemetry_readings', ['chamber_id', 'ts'], unique=False)
    op.create_index(op.f('ix_telemetry_readings_ts'), 'telemetry_readings', ['ts'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_version_id', sa.Integer(), nullable=False),
    sa.Column('chamber_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'QUEUED', 'RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED', 'FAILED', name='batch_status'), nullable=False),
    sa.Column('product_weight_kg', sa.Float(), nullable=True),
    sa.Column('yield_kg', sa.Float(), nullable=True),
    sa.Column('losses_percent', sa.Float(), nullable=True),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_batch_number'), 'batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_batches_chamber_id'), 'batches', ['chamber_id'], unique=False)
    op.create_index(op.f('ix_batches_recipe_version_id'), 'batches', ['recipe_version_id'], unique=False)
    op.create_index(op.f('ix_batches_status'), 'batches', ['status'], unique=False)
    op.create_table('recipe_approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_version_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='approval_decision'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_approvals_recipe_version_id'), 'recipe_approvals', ['recipe_version_id'], unique=False)
    op.create_table('batch_phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('phase_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('planned_duration_min', sa.Float(), nullable=True),
    sa.Column('actual_duration_min', sa.Float(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('set_t_chamber', sa.Float(), nullable=True),
    sa.Column('set_humidity', sa.Float(), nullable=True),
    sa.Column('set_smoke', sa.String(length=50), nullable=True),
    sa.Column('set_electro_voltage_kv', sa.Float(), nullable=True),
    sa.Column('set_fan_speed_percent', sa.Integer(), nullable=True),
    sa.Column('avg_t_chamber', sa.Float(), nullable=True),
    sa.Column('avg_t_product', sa.Float(), nullable=True),
    sa.Column('avg_humidity', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_phases_batch_id'), 'batch_phases', ['batch_id'], unique=False)
    op.create_table('batch_telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('t_chamber', sa.Float(), nullable=True),
    sa.Column('t_product', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('smoke_density', sa.Float(), nullable=True),
    sa.Column('electro_voltage', sa.Float(), nullable=True),
    sa.Column('electro_current', sa.Float(), nullable=True),
    sa.Column('fan_rpm', sa.Float(), nullable=True),
    sa.Column('door_open', sa.Boolean(), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=True),
    sa.Column('phase_progress', sa.Float(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_telemetry_batch_ts', 'batch_telemetry', ['batch_id', 'ts'], unique=False)
    op.create_index(op.f('ix_batch_telemetry_ts'), 'batch_telemetry', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_telemetry_ts'), table_name='batch_telemetry')
    op.drop_index('ix_batch_telemetry_batch_ts', table_name='batch_telemetry')
    op.drop_table('batch_telemetry')
    op.drop_index(op.f('ix_batch_phases_batch_id'), table_name='batch_phases')
    op.drop_table('batch_phases')
    op.drop_index(op.f('ix_recipe_approvals_recipe_version_id'), table_name='recipe_approvals')
    op.drop_table('recipe_approvals')
    op.drop_index(op.f('ix_batches_status'), table_name='batches')
    op.drop_index(op.f('ix_batches_recipe_version_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_chamber_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_number'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_telemetry_readings_ts'), table_name='telemetry_readings')
    op.drop_index('ix_telemetry_chamber_ts', table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    op.drop_index(op.f('ix_recipe_versions_status'), table_name='recipe_versions')
    op.drop_index(op.f('ix_recipe_versions_recipe_id'), table_name='recipe_versions')
    op.drop_table('recipe_versions')
    op.drop_index(op.f('ix_knowledge_attachments_article_id'), table_name='knowledge_attachments')
    op.drop_table('knowledge_attachments')
    op.drop_index(op.f('ix_recipes_status'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_slug'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_product_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_knowledge_articles_slug'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_category'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_chambers_slug'), table_name='chambers')
    op.drop_index(op.f('ix_chambers_manufacturer_id'), table_name='chambers')
    op.drop_table('chambers')
    op.drop_index(op.f('ix_audit_logs_ts'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_manufacturers_slug'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_is_our_brand'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_is_competitor'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_ingredients_type'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_slug'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_brines_slug'), table_name='brines')
    op.drop_table('brines')
    # ### end Alembic commands ###
