"""drop_entity_links

Revision ID: 887d59aaa35f
Revises: 36366251cf5d
Create Date: 2026-06-14 21:36:16.457150+03:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '887d59aaa35f'
down_revision = '36366251cf5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_links_source_type_source_id', table_name='entity_links')
    op.drop_index('ix_entity_links_target_type_target_id', table_name='entity_links')
    op.drop_table('entity_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relation', sa.VARCHAR(length=50), server_default=sa.text("'mentions'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='entity_links_pkey'),
    sa.UniqueConstraint('source_type', 'source_id', 'target_type', 'target_id', 'relation', name='uq_entity_link')
    )
    op.create_index('ix_entity_links_target_type_target_id', 'entity_links', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_entity_links_source_type_source_id', 'entity_links', ['source_type', 'source_id'], unique=False)
    # ### end Alembic commands ###
