"""add competitors

Revision ID: d87feba3f3c5
Revises: 529ad78b1f74
Create Date: 2026-06-03 13:51:32.810656+03:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87feba3f3c5'
down_revision = '529ad78b1f74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('is_main_competitor', sa.Boolean(), nullable=False),
    sa.Column('client_count', sa.Integer(), nullable=True),
    sa.Column('recipe_count', sa.Integer(), nullable=True),
    sa.Column('warranty_years', sa.Integer(), nullable=True),
    sa.Column('has_cloud', sa.Boolean(), nullable=True),
    sa.Column('has_mobile_app', sa.Boolean(), nullable=True),
    sa.Column('has_remote_monitoring', sa.Boolean(), nullable=True),
    sa.Column('has_video_camera', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_slug'), 'competitors', ['slug'], unique=True)
    op.create_table('competitor_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_load_kg', sa.Integer(), nullable=True),
    sa.Column('power_kw', sa.Integer(), nullable=True),
    sa.Column('voltage_v', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'products', 'recipes', ['base_recipe_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'recipes', 'recipe_versions', ['current_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_table('competitor_problems')
    op.drop_table('competitor_models')
    op.drop_index(op.f('ix_competitors_slug'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###
